/* eslint-disable */
// @ts-nocheck
// Generated by TanStack Router. The Vite plugin refreshes this file.
import { Route as rootRoute } from './routes/__root'
import { Route as indexRouteImport } from './routes/index'

const indexRoute = indexRouteImport.update({
  getParentRoute: () => rootRoute,
  id: '/',
  path: '/'
} as any)

export const routeTree = rootRoute._addFileChildren({ '/': indexRoute })
