/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsTabRouteImport } from './routes/settings.$tab'
import { Route as RRoomRouteImport } from './routes/r.$room'
import { Route as BBotSSectionRouteImport } from './routes/b.$bot.s.$section'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTabRoute = SettingsTabRouteImport.update({
  id: '/settings/$tab',
  path: '/settings/$tab',
  getParentRoute: () => rootRouteImport,
} as any)
const RRoomRoute = RRoomRouteImport.update({
  id: '/r/$room',
  path: '/r/$room',
  getParentRoute: () => rootRouteImport,
} as any)
const BBotSSectionRoute = BBotSSectionRouteImport.update({
  id: '/b/$bot/s/$section',
  path: '/b/$bot/s/$section',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/connect': typeof ConnectRoute
  '/onboarding': typeof OnboardingRoute
  '/r/$room': typeof RRoomRoute
  '/settings/$tab': typeof SettingsTabRoute
  '/b/$bot/s/$section': typeof BBotSSectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/connect': typeof ConnectRoute
  '/onboarding': typeof OnboardingRoute
  '/r/$room': typeof RRoomRoute
  '/settings/$tab': typeof SettingsTabRoute
  '/b/$bot/s/$section': typeof BBotSSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/connect': typeof ConnectRoute
  '/onboarding': typeof OnboardingRoute
  '/r/$room': typeof RRoomRoute
  '/settings/$tab': typeof SettingsTabRoute
  '/b/$bot/s/$section': typeof BBotSSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/connect'
    | '/onboarding'
    | '/r/$room'
    | '/settings/$tab'
    | '/b/$bot/s/$section'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/connect'
    | '/onboarding'
    | '/r/$room'
    | '/settings/$tab'
    | '/b/$bot/s/$section'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/connect'
    | '/onboarding'
    | '/r/$room'
    | '/settings/$tab'
    | '/b/$bot/s/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ConnectRoute: typeof ConnectRoute
  OnboardingRoute: typeof OnboardingRoute
  RRoomRoute: typeof RRoomRoute
  SettingsTabRoute: typeof SettingsTabRoute
  BBotSSectionRoute: typeof BBotSSectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$tab': {
      id: '/settings/$tab'
      path: '/settings/$tab'
      fullPath: '/settings/$tab'
      preLoaderRoute: typeof SettingsTabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$room': {
      id: '/r/$room'
      path: '/r/$room'
      fullPath: '/r/$room'
      preLoaderRoute: typeof RRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$bot/s/$section': {
      id: '/b/$bot/s/$section'
      path: '/b/$bot/s/$section'
      fullPath: '/b/$bot/s/$section'
      preLoaderRoute: typeof BBotSSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ConnectRoute: ConnectRoute,
  OnboardingRoute: OnboardingRoute,
  RRoomRoute: RRoomRoute,
  SettingsTabRoute: SettingsTabRoute,
  BBotSSectionRoute: BBotSSectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
